CleanArchaticture/Controllers/AmenityController.cs
using CleanArchaticture.Application.Common.Interfaces;
using CleanArchaticture.Domain.Model;
using CleanArchaticture.Infrastructure.Data;
using CleanArchaticture.Infrastructure.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using System.Net.Mime;
using System.Security.AccessControl;

namespace CleanArchaticture.Controllers
{
    
    public class AmenityController : Controller
    {
      private readonly IUnitOfWork _IunitOfWork;
        public AmenityController(IUnitOfWork iunitOfWork)
        {
          _IunitOfWork = iunitOfWork;
        }
        public IActionResult Index()
        {
            //var Amenitys = _context.Amenitys.ToList();
            //after include

            var Amenitys = _IunitOfWork.Amenity.GetAll(IncludeProperties: "Villa");
            return View(Amenitys);
        }
        [HttpGet]
        public IActionResult Create()
        {
            IEnumerable<SelectListItem> list = _IunitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()

            });

            ViewBag.Villalist = list;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Amenity objNumbers)
        {
            ModelState.Remove("Villa");
            if (ModelState.IsValid)
            {
                _IunitOfWork.Amenity.Add(objNumbers);
                _IunitOfWork.Save();
                TempData["success"] = "The Villa Has been Created Successfully";
                return RedirectToAction("Index");
            }

            else
            //TempData["error"] = "The Villa Could'nt be created";
            return View(objNumbers);
        }

        [HttpGet]
                public IActionResult Update(int id)

                {
                    var obj = _IunitOfWork.Amenity.Get(x => x.Id == id, IncludeProperties: "Villa");

                    if (obj==null)
                    {
                        return NotFound();
                    }

                    ViewBag.Villalist = _IunitOfWork.Villa.GetAll().Select(u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id.ToString() 
                    });

                    return View(obj);


                    //before unitofwork

                    //// Villa? obj = _context.villas.FirstOrDefault(x => x.Id == id);
                    ////get data from feild by ID
                    //Amenitys? obj = _IunitOfWork.Amenitys.Get(x => x.Amenity == id);
                    //if (obj == null)
                    //{
                    //    return RedirectToAction("Error", "Home");
                    //}

                    ////get data from model to show it in drwodown list
                    //ViewBag.Villalist = _IunitOfWork.Villa.GetAll().Select(u => new SelectListItem
                    //    {
                    //        Text = u.Name,
                    //        Value = u.Id.ToString()

                    //    });






                    //return View(obj); 
                }

                [HttpPost]

                public IActionResult Update(Amenity obNumbers)
                {


                    if (ModelState.IsValid)
                    {
                        var VillanumberfromDB =
                            _IunitOfWork.Amenity.Get(u => u.Id == obNumbers.Id);
                        if (VillanumberfromDB==null)
                        {
                            return NotFound();
                        }
                        VillanumberfromDB.Id=obNumbers.Id;
                        VillanumberfromDB.Name=obNumbers.Name;

                            _IunitOfWork.Amenity.Update(VillanumberfromDB);
                            _IunitOfWork.Save();

                        //before using UnitOfWork

                        //_IunitOfWork.Amenitys.Update(obNumbers);
                        //_IunitOfWork.Save();
                        //return RedirectToAction("Index");





            }
                              //dropdown 
                                ViewBag.Villalist = _IunitOfWork.Villa.GetAll().Select(x => new SelectListItem
                                {
                                    Text = x.Name,
                                    Value = x.Id.ToString()
                                    

                                });

                           return RedirectToAction("Index");


        }

        public IActionResult Delete(int id)
        {
            var obj = _IunitOfWork.Amenity.Get(x=>x.Id==id);
            if (obj!=null)
            {
                _IunitOfWork.Amenity.Remove(obj);
                TempData["success"] = "The Villa Has been Deleted Successfully";
                _IunitOfWork.Save();

            }
            else
            {
                TempData["error"] = "The Villa could'nt be Deleted";
                
            }
                return RedirectToAction("Index"); 

        }
    }
}

CleanArchaticture/Views/Amenity/Create.cshtml
@model Amenity 
@* @model VillaNumberVM  *@
<div class="card-header bg-success bg-gradient ml-0 py-0">

    <div class="row">

        <div class="col-12 text-center">
            <h2 class="text-white py-2"> Create Villa Number</h2>
        </div>
    </div>

</div>

<div class="card-body border p-4">
    <form method="post">
        <div class="p-3">

            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-floating py-1 col-12">
                <select asp-for=" VillaId" asp-items="@ViewBag.Villalist" class="form-select border shadow">
                    <option disabled selected> --select option--</option>
                </select>
                @* <input type="text" asp-for="VillaId" id="VillaId" class="form-control border box-shadow" /> *@
                <label asp-for="VillaId" class="ms-2"></label>
                <span asp-validation-for="VillaId" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="number" asp-for="Id" id="Id" disabled class="form-control border box-shadow" />
                <label asp-for="Id" class="ms-2"></label>
                <span asp-validation-for="Id" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="text" asp-for="Name" id="SpecialDetails" class="form-control border box-shadow" />
                <label asp-for="Name" class="ms-2"></label>
                <span asp-validation-for="Name" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="text" asp-for="Description" id="SpecialDetails" class="form-control border box-shadow" />
                <label asp-for="Description" class="ms-2"></label>
                <span asp-validation-for="Description" class="text-danger"></span>

            </div>
            <div class="row pt-2">
                <div class="col-2 col-md-3">
                    <button type="submit" class="btn btn-success w-100" style="margin:10px auto ">
                        <i class="bi bi-plus-circle"> Create</i>
                    </button>
                </div>

                <div class="col-6   col-md-3">
                    <a asp-action="Index" asp-controller="Amenity" class="btn btn-secondary w-100" style="margin-top:10px">
                        <i class="bi bi-x-circle" style="margin-right:10px"></i>Cancel
                    </a>
                </div>
            </div>


        </div>
    </form>
</div>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }


}

CleanArchaticture/Views/Amenity/Index.cshtml
@model List<Amenity>


<div class="card-header bg-success bg-gradient ml-0 py-0">

    <div class="row">

        <div class="col-12 text-center">
            <h2 class="text-white py-2"> Amenity List</h2>
        </div>
    </div>

</div>


<div class="card-body border p-4">


    <div class="row pb-3">
        <div class=" col-6 offset-6 text-end">
            <a asp-action="Create" asp-controller="Amenity" class="btn btn-secondary">
                <i class="bi bi-plus-circle"></i>     Create New Amenity
            </a>
        </div>
    </div>

    <table class="table table-bordered table-sthiped">
        <thead>

            <tr>
                <th>Amenity Id</th>
                <th>Villa Name</th> 
                <th>Amenity Name</th>
                <th> Descreption</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>



                    <td>@item.Id</td>
                    <td>@item.Villa.Name</td>
                    <td>@item.Name</td>
                    <td>@item.Description</td>


                    <td>
                        <div class="w-75 btn-group  ">
                            <a asp-action="Update" asp-controller="Amenity" asp-route-id="@item.Id" style="margin-right:10px" class="btn btn-success mx-2">

                                <i class="bi bi-pencil-square"></i> Edit

                            </a>
                            <a asp-action="Delete" asp-controller="Amenity" asp-route-id="@item.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-person-x-fill"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }

        </tbody>

    </table>
</div>

CleanArchaticture/Views/Amenity/Update.cshtml
@model Amenity
@* @model VillaNumberVM  *@
<div class="card-header bg-success bg-gradient ml-0 py-0">

    <div class="row">

        <div class="col-12 text-center">
            <h2 class="text-white py-2"> Update Villa Number</h2>
        </div>
    </div>

</div>

<div class="card-body border p-4">
    <form method="post">
        <div class="p-3">

            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-floating py-1 col-12">
                <select asp-for=" VillaId" asp-items="@ViewBag.Villalist" class="form-select border shadow">
                    <option disabled selected> --select option--</option>
                </select>
                @* <input type="text" asp-for="VillaId" id="VillaId" class="form-control border box-shadow" /> *@
                <label asp-for="VillaId" class="ms-2"></label>
                <span asp-validation-for="VillaId" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="number" asp-for="Id" readonly id="Id" class="form-control border box-shadow" />
                <label asp-for="Id" class="ms-2"></label>
                <span asp-validation-for="Id" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="text" asp-for="Name" id="SpecialDetails" class="form-control border box-shadow" />
                <label asp-for="Name" class="ms-2"></label>
                <span asp-validation-for="Name" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="text" asp-for="Description" id="descreption" class="form-control border box-shadow" />
                <label asp-for="Description" class="ms-2"></label>
                <span asp-validation-for="Description" class="text-danger"></span>

            </div>
            <div class="row pt-2">
                <div class="col-2 col-md-3">
                    <button type="submit" class="btn btn-success w-100" style="margin:10px auto ">
                        <i class="bi bi-plus-circle"> Update</i>
                    </button>
                </div>

                <div class="col-6   col-md-3">
                    <a asp-action="Index" asp-controller="VillaNumber" class="btn btn-secondary w-100" style="margin-top:10px">
                        <i class="bi bi-x-circle" style="margin-right:10px"></i>Cancel
                    </a>
                </div>
            </div>


        </div>
    </form>
</div>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }


}