CleanArchaticture/Controllers/VillaController.cs
using CleanArchaticture.Application.Common.Interfaces;
using CleanArchaticture.Domain.Model;
using CleanArchaticture.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using System.Security.AccessControl;

namespace CleanArchaticture.Controllers
{
    
    public class VillaController : Controller
    {
      private readonly IUnitOfWork _IunitOfWork; //to deal with database
      private readonly IWebHostEnvironment _webHostEnvironment;//to deal with images and add it
    

        public VillaController(IUnitOfWork iunitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            this._IunitOfWork = iunitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var villas = _IunitOfWork.Villa.GetAll();
            return View(villas);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Villa villa)    
        {
            if (villa.Name == villa.Description)
            {
                    ModelState.AddModelError("","The Name and Description can't be the same");
            }   

            if (ModelState.IsValid)
            {

                if ( villa.Image!=null)
                {

                    //to add image in create form
                    //1 open folder in wwwroot
                    //2 add fake enetity and make it(Not Mapped) 
                    //3 create this code(Above ) 
                    //4 put feild for it in view 


                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(villa.Image.FileName);
                    string imagepath = Path.Combine(_webHostEnvironment.WebRootPath, @"Image\VillaImage");
                    using (var fileStream =new FileStream(Path.Combine(imagepath,fileName),FileMode.Create))
                    {
                        villa.Image.CopyTo(fileStream);
                    }

                    villa.ImageUrl = @"\Image\VillaImage" + fileName;
                }
                else
                {
                    villa.ImageUrl = "https://placehold.co/600x400";
                }


                _IunitOfWork.Villa.Add(villa);
                _IunitOfWork.Save();
                TempData["success"] = "The Villa Has been Created Successfully";

                return RedirectToAction("Index");
            }

            else
            TempData["error"] = "The Villa Could'nt be created";
                return View(villa);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
           // Villa? obj = IunitOfWork.villas.FirstOrDefault(x => x.Id == id);
           Villa? obj = _IunitOfWork.Villa.Get(u=>u.Id==id);
          

            if (obj==null)  
            {
                return RedirectToAction("Error","Home");
            }

            return View(obj);
        }

        [HttpPost]

        public IActionResult Update(Villa villa)
        {
           

            if (ModelState.IsValid)
            {
                _IunitOfWork.Villa.Update(villa);
                _IunitOfWork.Save();
                return RedirectToAction("Index");
            }
            else
                return View(villa);



        }

        public IActionResult Delete(int id)
        {
            var obj = _IunitOfWork.Villa.Get(x=>x.Id==id);
            if (obj!=null)
            {
                _IunitOfWork.Villa.Remove(obj);
                TempData["success"] = "The Villa Has been Deleted Successfully";
                _IunitOfWork.Save();

            }
            else
            {
                TempData["error"] = "The Villa could'nt be Deleted";
                
            }
                return RedirectToAction("Index"); 

        }
    }
}

CleanArchaticture/Views/Villa/Create.cshtml
@model Villa
<div class="card-header bg-success bg-gradient ml-0 py-0">

    <div class="row">

        <div class="col-12 text-center">
            <h2 class="text-white py-2"> Create Villa</h2>
        </div>
    </div>

</div>

<div class="card-body border p-4">
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="p-3">
            
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-floating py-1 col-12">
                <input type="text" asp-for="Name" id="name" class="form-control border box-shadow"/>
                <label asp-for="Name" class="ms-2"></label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating py-1 col-12">
                <input type="text" asp-for="Description" id="name" class="form-control border box-shadow"/>
                <label asp-for="Description" class="ms-2"></label>
                <span asp-validation-for="Description" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="number" asp-for="Price" id="name" class="form-control border box-shadow"/>
                <label asp-for="Price" class="ms-2"></label>
                <span asp-validation-for="Price" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="number" asp-for="Sqft" id="name" class="form-control border box-shadow"/>
                <label asp-for="Sqft" class="ms-2"></label>
                <span asp-validation-for="Sqft" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input type="number" asp-for="Occupancy" id="name" class="form-control border box-shadow"/>
                <label asp-for="Occupancy" class="ms-2"></label>
                <span asp-validation-for="Occupancy" class="text-danger"></span>

            </div>
            <div class="form-floating py-1 col-12">
                <input  asp-for="ImageUrl" hidden id="ImageUrl" class="form-control border box-shadow"/>
                <input  asp-for="Image"  id="ImageUrl" class="form-control border box-shadow"/>
                <label asp-for="ImageUrl" class="ms-2"></label>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>

            </div>

            <div class="row pt-2">
                <div class="col-2 col-md-3">
                    <button type="submit" class="btn btn-success w-100" style="margin:10px auto ">
                        <i class="bi bi-plus-circle"> Create</i>
                    </button>
                </div>

                <div class="col-6   col-md-3">
                    <a asp-action="Index" asp-controller="Villa" class="btn btn-secondary w-100" style="margin-top:10px">
                        <i class="bi bi-x-circle" style="margin-right:10px"></i>Cancel
                    </a>
                </div>
            </div>


        </div>
    </form>
</div>

@section Scripts
{
    @{
    <partial name="_ValidationScriptsPartial"/> 
    }


}

CleanArchaticture/Views/Villa/Index.cshtml
@model List<CleanArchaticture.Domain.Model.Villa>

    <div class="card-header bg-success bg-gradient ml-0 py-0">

        <div class="row">

            <div class="col-12 text-center">
            <h2 class="text-white py-2"> Villa List</h2>
            </div>
        </div>

    </div>


<div class="card-body border p-4">


    <div class="row pb-3">
        <div class=" col-6 offset-6 text-end">
            <a  asp-action="Create" asp-controller="Villa" class="btn btn-secondary">
                <i class="bi bi-plus-circle"></i>     Create New Villa
            </a>
        </div>
    </div>

    <table class="table table-bordered table-sthiped">
        <thead>

            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Sqft</th>
                <th>Occupancy</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>


                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.Sqft</td>
                    <td>@item.Occupancy</td>
                    <td>
                        <div class="w-75 btn-group  ">
                            <a asp-action="Update" asp-controller="Villa" asp-route-Id="@item.Id" style="margin-right:10px" class="btn btn-success mx-2">
                               
                                <i class="bi bi-pencil-square"></i> Edit
                                                                    
                            </a>
                            <a asp-action="Delete" asp-controller="Villa" asp-route-Id="@item.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-person-x-fill"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }

        </tbody>

    </table>
</div>

CleanArchaticture/Views/Villa/Update.cshtml
@model Villa
<div class="card-header bg-success bg-gradient ml-0 py-0">

    <div class="row">

        <div class="col-12 text-center">
            <h2 class="text-white py-2"> Update Villa</h2>
        </div>
    </div>

</div>

<div class="card-body border p-4">
    <form method="post" class="row" enctype="multipart/form-data">
        
        <div class="col-10">
            <div class="p-3">
                <input asp-for="Id" hidden />
                <div asp-validation-summary="ModelOnly"></div>
                <div class="form-floating py-1 col-12">
                    <input type="text" asp-for="Name" id="name" class="form-control border box-shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input type="text" asp-for="Description" id="name" class="form-control border box-shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input type="number" asp-for="Price" id="name" class="form-control border box-shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>


                </div>
                <div class="form-floating py-1 col-12">
                    <input type="number" asp-for="Sqft" id="name" class="form-control border box-shadow" />
                    <label asp-for="Sqft" class="ms-2"></label>
                    <span asp-validation-for="Sqft" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input type="number" asp-for="Occupancy" id="name" class="form-control border box-shadow" />
                    <label asp-for="Occupancy" class="ms-2"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>

                </div>

                <div class="form-floating py-1 col-12">
                    <input asp-for="Image" class="form-control border shadow "/>
                    <input asp-for="ImageUrl" hidden id="ImageUrl" class="form-control border box-shadow"/>
                    <label asp-for="ImageUrl" class="ms-2"></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>

                </div>

                <div class="row pt-2">
                    <div class="col-2 col-md-3">
                        <button type="submit" class="btn btn-success w-100" style="margin:10px auto ">
                            <i class="bi bi-plus-circle"> Update</i>
                        </button>
                    </div>

                    <div class="col-6   col-md-3">
                        <a asp-action="Index" asp-controller="Villa" class="btn btn-secondary w-100" style="margin-top:10px">
                            <i class="bi bi-x-circle" style="margin-right:10px"></i>Cancel
                        </a>
                    </div>
                </div>


            </div>
        </div>
        <div class="col-2">
            <img src="@Model.ImageUrl" width="100%" 
                 style=" border-radius:5px;border:1px solid #bbb9b9"/> 

        </div> 
    </form>
</div>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }


}